language: node_js
sudo: false
node_js:
  - "node"
  - "iojs"
services:
  - mongodb
before_install:
  - export PATH=./node_modules/.bin/:$PATH
  - npm install node-gyp -g
install:
  - npm install
before_script:
  - node-pre-gyp clean
  - node-gyp clean
script:
  - npm test
  - node-pre-gyp clean
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8